import '../globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col bg-zinc-900 text-zinc-100">
        <header className="p-4 text-center text-xl font-semibold bg-zinc-600">
          Header
        </header>

        <main className="flex-1 p-4">{children}</main>

        <footer className="p-4 text-center text-xl font-semibold bg-zinc-600">
          Footer
        </footer>
      </body>
    </html>
  );
}
